package de.htwg_konstanz.ebus.wholesaler.ws.updatecatalog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "UpdateCatalogWebservice", targetNamespace = "http://localhost:8084/EBUT_Wholesaler/updatecatalog")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateCatalog {

    /**
     *
     * @param updateRequest
     * @return returns
     * de.htwg_konstanz.ebus.wholesaler.updatecatalog.UpdateResponse
     * @throws AuthenticationFault
     */
    @WebMethod(action = "urn:#updateCatalog")
    @WebResult(name = "updateResponse", targetNamespace = "http://localhost:8084/EBUT_Wholesaler/updatecatalog", partName = "updateResponse")
    public UpdateResponse updateCatalog(
            @WebParam(name = "updateRequest", targetNamespace = "http://localhost:8084/EBUT_Wholesaler/updatecatalog", partName = "updateRequest") UpdateRequest updateRequest)
            throws AuthenticationFault;

}
